"use client";
import Footer from "@/components/shared/Footer";
import Navigation from "@/components/shared/Navigation"; // Make sure to import the Navigation component
import AuthProvider from "@/context/AuthProvider";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation"; // Use usePathname from next/navigation
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Job-portal",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current pathname

  // Check if the current route should have the navbar
  const showNavbar = pathname.startsWith("/dashboard"); // Adjust the path as needed

  return (
    <html lang="en">
      <body
        className={`${inter.className} relative h-full font-sans antialiased`}
      >
        <AuthProvider>
          <main className="relative flex flex-col min-h-screen">
            {/* Conditionally render Navbar */}
            {!showNavbar && <Navigation />}
            <div className="flex-grow flex-1"> {children}</div>
            {/* Footer */}
            <Footer />
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
